[package]
name = "dash9-tui"
description = "Ratatui terminal frontend for dash9"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
crossterm = { workspace = true }
dash9-core = { workspace = true }
ratatui = { workspace = true }
